# Generated by Django 5.1.7 on 2025-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], default='purchase', max_length=10),
        ),
    ]
